services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: tracker_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tracker

  nginx:
    image: nginx:alpine
    container_name: tracker_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - tracker
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: tracker_mysql
    environment:
      MYSQL_DATABASE: tracker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 111111
    volumes:
      - tracker_db:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - tracker

  vue:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile
    container_name: tracker_vue
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - tracker
    depends_on:
      - nginx

networks:
  tracker:
    driver: bridge

volumes:
  tracker_db: